image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'Deployment to Production'
        deployment: production
        script:
          - pipe: atlassian/ftp-deploy:0.3.5
            variables:
              USER: chiayila
              PASSWORD: wpvyrn520
              SERVER: 198.55.121.39
              REMOTE_PATH: /public_html/mooney
